using UnityEngine;
using System.Collections.Generic;

/// <summary>
/// Component that allows objects to hear and react to sound events from the NoiseManager.
/// Guards use this to investigate sounds and detect the player through audio.
/// </summary>
public class SoundListener : MonoBehaviour
{
    [Header("Hearing Settings")]
    [Tooltip("Minimum sound intensity required to hear a sound")]
    public float HearingSensitivityThreshold = 1.0f;
    
    [Tooltip("Maximum distance at which sounds can be heard")]
    public float MaxHearingRange = 8f;
    
    [Tooltip("Layer mask for walls that block sound")]
    public LayerMask WallLayerMask = -1;
    
    [Header("Sound Investigation")]
    [Tooltip("How long to investigate a sound before giving up (set to 0 to disable timer)")]
    public float InvestigationDuration = 0f;
    
    [Tooltip("How close to get to a sound source before stopping")]
    public float InvestigationTolerance = 0.5f;
    
    [Header("Debug")]
    [Tooltip("Show hearing range in Scene view")]
    public bool ShowHearingRange = true;
    
    [Tooltip("Enable debug logs for sound detection")]
    public bool EnableDebugLogs = false;
    
    // Private variables
    private EnemyMovement enemyMovement;
    private Vector3 lastHeardSoundPosition;
    private float lastSoundTime;
    private bool isInvestigatingSound = false;
    private float investigationTimer;
    
    // Sound event data
    private struct HeardSound
    {
        public Vector3 position;
        public float intensity;
        public float timeHeard;
    }
    
    private List<HeardSound> recentSounds = new List<HeardSound>();
    
    void Start()
    {
        // Subscribe to sound events
        NoiseManager.OnSoundGenerated += OnSoundHeard;
        
        // Get reference to enemy movement component
        enemyMovement = GetComponent<EnemyMovement>();
        if (enemyMovement == null)
        {
            Debug.LogWarning("SoundListener requires EnemyMovement component for full functionality");
        }
        
        // Set up wall layer mask if not configured
        if (WallLayerMask == -1)
        {
            WallLayerMask = LayerMask.GetMask("Wall");
        }
    }
    
    void OnDestroy()
    {
        // Unsubscribe from events
        NoiseManager.OnSoundGenerated -= OnSoundHeard;
    }
    
    void Update()
    {
        // Handle sound investigation timer (only if duration is set)
        if (isInvestigatingSound && InvestigationDuration > 0)
        {
            investigationTimer -= Time.deltaTime;
            if (investigationTimer <= 0)
            {
                StopInvestigatingSound();
            }
        }
        
        // Clean up old sounds
        CleanupOldSounds();
    }
    
    /// <summary>
    /// Called when a sound event is generated by the NoiseManager
    /// </summary>
    private void OnSoundHeard(SoundEvent soundEvent)
    {
        // Calculate distance to sound source
        float distanceToSound = Vector3.Distance(transform.position, soundEvent.Position);
        
        // Check if sound is within hearing range
        if (distanceToSound > MaxHearingRange)
        {
            return; // Too far to hear
        }
        
        // Check if walls block the sound path
        if (IsSoundBlockedByWalls(soundEvent.Position))
        {
            if (EnableDebugLogs)
            {
                Debug.Log($"[SoundListener] Sound blocked by walls from {soundEvent.Position}");
            }
            return; // Sound is blocked by walls
        }
        
        // Calculate effective sound intensity at this distance
        float effectiveIntensity = CalculateEffectiveIntensity(soundEvent.Intensity, distanceToSound);
        
        // Check if sound is loud enough to hear
        if (effectiveIntensity < HearingSensitivityThreshold)
        {
            return; // Too quiet to hear
        }
        
        // We can hear the sound!
        if (EnableDebugLogs)
        {
            Debug.Log($"[SoundListener] Heard sound at {soundEvent.Position} | intensity={effectiveIntensity:F2} | distance={distanceToSound:F2}");
        }
        
        // Report sound to AlertManager
        if (AlertManager.Instance != null)
        {
            AlertManager.Instance.OnSoundHeard(soundEvent.Position, effectiveIntensity);
        }
        
        // Store the sound event
        HeardSound heardSound = new HeardSound
        {
            position = soundEvent.Position,
            intensity = effectiveIntensity,
            timeHeard = Time.time
        };
        recentSounds.Add(heardSound);
        
        // Start investigating the sound
        StartInvestigatingSound(soundEvent.Position);
    }
    
    /// <summary>
    /// Checks if walls block the path between listener and sound source
    /// </summary>
    private bool IsSoundBlockedByWalls(Vector3 soundPosition)
    {
        Vector3 direction = (soundPosition - transform.position).normalized;
        float distance = Vector3.Distance(transform.position, soundPosition);
        
        // Cast a ray from listener to sound source
        RaycastHit2D hit = Physics2D.Raycast(transform.position, direction, distance, WallLayerMask);
        
        // If we hit a wall, the sound is blocked
        return hit.collider != null;
    }
    
    /// <summary>
    /// Calculates the effective sound intensity at the listener's position
    /// </summary>
    private float CalculateEffectiveIntensity(float baseIntensity, float distance)
    {
        // Simple inverse square law for sound attenuation
        // Sound gets weaker with distance
        float attenuation = 1f / (1f + distance * distance * 0.1f);
        return baseIntensity * attenuation;
    }
    
    /// <summary>
    /// Starts investigating a sound at the given position
    /// </summary>
    private void StartInvestigatingSound(Vector3 soundPosition)
    {
        lastHeardSoundPosition = soundPosition;
        lastSoundTime = Time.time;
        isInvestigatingSound = true;
        investigationTimer = InvestigationDuration;
        
        if (EnableDebugLogs)
        {
            Debug.Log($"[SoundListener] Starting investigation of sound at {soundPosition}");
        }
        
        // Notify enemy movement to investigate
        if (enemyMovement != null)
        {
            // We'll need to add a method to EnemyMovement to handle sound investigation
            // For now, we'll store the position for the enemy to check
        }
    }
    
    /// <summary>
    /// Stops investigating sounds
    /// </summary>
    private void StopInvestigatingSound()
    {
        isInvestigatingSound = false;
        if (EnableDebugLogs)
        {
            Debug.Log("[SoundListener] Stopped investigating sound");
        }
    }
    
    /// <summary>
    /// Cleans up old sound events from memory
    /// </summary>
    private void CleanupOldSounds()
    {
        float currentTime = Time.time;
        recentSounds.RemoveAll(sound => currentTime - sound.timeHeard > 10f); // Keep sounds for 10 seconds
    }
    
    /// <summary>
    /// Public method to check if the listener is currently investigating a sound
    /// </summary>
    public bool IsInvestigatingSound()
    {
        return isInvestigatingSound;
    }
    
    /// <summary>
    /// Public method to get the last heard sound position
    /// </summary>
    public Vector3 GetLastHeardSoundPosition()
    {
        return lastHeardSoundPosition;
    }
    
    /// <summary>
    /// Public method to get the time when the last sound was heard
    /// </summary>
    public float GetLastSoundTime()
    {
        return lastSoundTime;
    }
    
    /// <summary>
    /// Draws the hearing range in the Scene view
    /// </summary>
    void OnDrawGizmos()
    {
        if (!ShowHearingRange) return;
        
        // Draw hearing sensitivity range
        Gizmos.color = new Color(0f, 1f, 0f, 0.2f);
        Gizmos.DrawWireSphere(transform.position, HearingSensitivityThreshold);
        
        // Draw max hearing range
        Gizmos.color = new Color(0f, 0.8f, 0f, 0.1f);
        Gizmos.DrawWireSphere(transform.position, MaxHearingRange);
        
        // Draw line to last heard sound if investigating
        if (isInvestigatingSound)
        {
            Gizmos.color = Color.yellow;
            Gizmos.DrawLine(transform.position, lastHeardSoundPosition);
            Gizmos.DrawWireSphere(lastHeardSoundPosition, 0.5f);
        }
    }
}
